The name of the branch is commited

diff --git a/pre-receive b/pre-receive
--- a/pre-receive
+++ b/pre-receive
@@ -3,13 +3,13 @@ Copy code
 
 while read oldrev newrev refname; do
     # Check if changes are being pushed to a branch other than 'main'
-    if [[ "$refname" != "refs/heads/test/commit_to_config" && "$refname" == refs/heads/* ]]; then
-        # Check if 'config.yml' is modified
-        if git diff --name-only origin/main test/commit_to_config | grep -q '^config/config-aqua.yaml$'; then
-            echo "Error: Changes to 'config.yml' are only allowed on the 'main' branch."
-            exit 1
-        fi
+    #if [[ "$refname" != "refs/heads/test/commit_to_config" && "$refname" == refs/heads/* ]]; then
+    # Check if 'config.yml' is modified
+    if git diff --name-only origin/main test/commit_to_config | grep -q '^config/config-aqua.yaml$'; then
+        echo "Error: Changes to 'config.yml' are only allowed on the 'main' branch."
+        exit 1
     fi
+    #fi
 done
 
 exit 0
